name = "VanillaPluh"
author = "Skiletro"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96a66160d34c51f5e2b034afd0b0983ae1e4d8e449fbefa6ac2526ceda0803bd"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
