name = "VanillaPluh"
author = "Skiletro"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648c40fc1f38909a0dbbbbcdf09ca8695352e814a3d7b5e0bcc69f742471b2f2"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
