mobhealthbar.hpbar.selected=4 #int | default: 1
mobhealthbar.hpbar.xpos=0 #int | default: 0
mobhealthbar.hpbar.ypos=6 #int | default: 0
mobhealthbar.hpbar.render_distance=3000 #int | default: 2000
mobhealthbar.hpbar.scale=0.6499999999999997 #double | default: 1.0d
mobhealthbar.hpbar.toggle=true #boolean | default: true
mobhealthbar.hpbar.show_name=false #boolean | default: true
mobhealthbar.hpbar.show_hp=true #boolean | default: true
mobhealthbar.hpbar.show_on_aggro=true #boolean | default: false
mobhealthbar.hpbar.blacklist=ender_dragon #String | default: ender_dragon
mobhealthbar.hpbar.bar=true #boolean | default: true
mobhealthbar.hpbar.damaged=false #boolean | default: false
mobhealthbar.hpbar.hovered=true #boolean | default: false
